pip install torch==2.0.1
pip install tensorboard
pip install packaging
pip install g2p_en
pip install pandas
pip install pillow
pip install torchvision
pip install ftfy
pip install humanfriendly
pip install typeguard==2.13.3
pip install scikit-learn
pip install librosa
pip install kaldiio
pip install resampy --user
pip install omegaconf
pip install matplotlib
pip install einops
pip install h5py
pip install torchaudio
pip install torchlibrosa
pip install transformers==4.30.2
pip install wget
pip install beartype
pip install torch_complex
pip install pystoi
pip install pesq
pip install resampy
pip install datasets
pip install scikit-image
pip install ssr_eval